version: "3.7"

services:
  frontend:
    build:
      context: ./css-styles
      dockerfile: Dockerfile.dev
    command: sleep infinity
    env_file:
      - ./css-styles/.env/dev.injected.env
    image: video_frontend_dev
    ports:
      - 3000:3000
    volumes:
      - ./css-styles:/app/src
